### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by wmcmurray**
*\*...sounds of a wild repository raising from the deads after 2 years...\**

Hello !

I fixed some small stuff, here is the recap :

1 - There was a dev dependency missing in packages.json
2 - I changed the default API version to 3 because v2 will be destroyed in about 2 or 3 weeks : https://dev.twitch.tv/docs/#which-api-version-can-you-use
3 - I handled JSON.parse errors (because the //TODO comment annoyed me lol)
4 - I fixed API's errors handling because when the API return an error It has a different httpStatus than 200. Therefore this lib was not sending the API response at all (which looks like this : 
```
{
    error: "Bad Request",
    status: 400,
    message: "Invalid client id specified"
}
```
).

Please publish a new npm version if this get merged.

Thank you ! :)

### CODE REVIEW

**Comment by wmcmurray** [comment]
Oh and I just realized that the dev dependency I added is required in the test file BUT it doesn't seems to be used at all... Maybe you'll want to remove it completely ? (I don't know what this "sync" dependency does)

**Comment by medimatrix** [comment]
Thanks! I'll publish this on npm ASAP

**Comment by medimatrix** [comment]
I've published your changes as `twitch.tv` version `2.0.0`. Thanks again and sorry for the delay.

**Comment by wmcmurray** [comment]
Yay thanks man ! No stress, I use this only for a personal project so there was no hurry :slightly_smiling_face:

**Pull request merged**
